{{- if .Values.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "maintenance.fullname" . }}
  labels:
    {{- include "maintenance.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "maintenance.selectorLabels" . | nindent 4 }}
{{- end }}
