{{- if .Values.node.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clamav-node.fullname" . }}
  labels:
    {{- include "clamav-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.node.service.type }}
  ports:
    - port: {{ .Values.node.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "clamav-node.selectorLabels" . | nindent 4 }}
{{- end }}
