---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.zone }}
  labels: {{- include "selectorLabels" . | nindent 4 }}
data:
  databasePassword: {{ .Values.global.secrets.databasePassword | b64enc | quote }}
  databaseUser: {{  .Values.global.secrets.databaseUser | b64enc | quote }}
  databaseName: {{  .Values.global.secrets.databaseName | b64enc | quote }}
  keycloakClientId: {{ .Values.global.secrets.keycloakClientId | b64enc | quote }}
  keycloakClientSecret: {{ .Values.global.secrets.keycloakClientSecret | b64enc | quote }}
  keycloakUrl: {{ .Values.global.secrets.keycloakUrl | b64enc | quote }}
  uiPrivateKey: {{ .Values.global.secrets.uiPrivateKey | b64enc | quote }}
  uiPublicKey: {{ .Values.global.secrets.uiPublicKey | b64enc | quote }}
