---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.zone }}
  labels: {{- include "labels" . | nindent 4 }}
data:
  POSTGRESQL_PASSWORD: {{ .Values.global.secrets.databasePassword | b64enc | quote }}
  POSTGRESQL_USER: {{  .Values.global.secrets.databaseUser | b64enc | quote }}
  FLYWAY_USER: {{  .Values.global.secrets.databaseUser | b64enc | quote }}
  FLYWAY_PASSWORD: {{ .Values.global.secrets.databasePassword | b64enc | quote }}
  POSTGRESQL_DATABASE: {{  .Values.global.secrets.databaseName | b64enc | quote }}
  KEYCLOAK_CLIENT_ID: {{ .Values.global.secrets.keycloakClientId | b64enc | quote }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.global.secrets.keycloakClientSecret | b64enc | quote }}
  KEYCLOAK_URL: {{ .Values.global.secrets.keycloakUrl | b64enc | quote }}
  PRIVATE_KEY: {{ .Values.global.secrets.uiPrivateKey | b64enc | quote }}
  PUBLIC_KEY: {{ .Values.global.secrets.uiPublicKey | b64enc | quote }}
  BCEID_WS_BASIC_AUTH_PASSWORD: {{ .Values.global.secrets.bceidWsAuthPassword | b64enc | quote }}
  BCEID_WS_BASIC_AUTH_USERNAME: {{ .Values.global.secrets.bceidWsAuthUserName | b64enc | quote }}
  BCEID_WS_ONLINE_SERVICE_ID: {{ .Values.global.secrets.bceidWsOnlineServiceId | b64enc | quote }}
  BCEID_WS_URL: {{ .Values.global.secrets.bceidWsUrl | b64enc | quote }}
