---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
  tags:
    - name: "{{ .Values.image.tag | default .Chart.AppVersion }}"
      from:
        kind: DockerImage
        name: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      referencePolicy:
        type: Local
