# PR specific values for fin-pay-transparency.
# Only override specific values for pr pipeline.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  secrets:
    databaseName: ~
    databaseUser: ~
    databasePassword: ~
    adminKeycloakUrl: ~
    adminKeycloakClientId: ~
    adminKeycloakClientSecret: ~
    keycloakClientId: ~
    keycloakClientSecret: ~
    keycloakUrl: ~
    uiPrivateKey: ~
    uiPublicKey: ~
    bceidWsAuthPassword: ~
    bceidWsAuthUserName: ~
    bceidWsUrl: ~
    bceidWsOnlineServiceId: ~
    externalConsumerApiKey: ~
    externalConsumerDeleteReportsApiKey: ~
    chesClientID: ~
    chesTokenURL: ~
    chesClientSecret: ~
    chesAPIURL: ~
    chesEmailRecipients: ~
  domain: "apps.silver.devops.gov.bc.ca" # it is required, apps.silver.devops.gov.bc.ca for silver cluster
  autoscaling:
    enabled: false
  crunchyEnabled: false
  databaseAlias: database


backend:
  deploymentStrategy: Recreate
  initResources:
    limits:
      cpu: 350m
      memory: 500Mi
    requests:
      cpu: 150m
      memory: 250Mi
  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 250Mi
  storage:
    enabled: true
    size: 50Mi
    accessMode: ReadWriteMany
  pdb: false

frontend:
  deploymentStrategy: Recreate
  resources:
    limits:
      cpu: 30m
      memory: 150Mi
    requests:
      cpu: 15m
      memory: 50Mi
  env:
    logLevel: info
  pdb: false

admin-frontend:
  deploymentStrategy: Recreate
  resources:
    limits:
      cpu: 30m
      memory: 150Mi
    requests:
      cpu: 15m
      memory: 50Mi
  env:
    logLevel: info
  pdb: false

crunchy:
  enabled: false

doc-gen-service:
  enabled: true
  deploymentStrategy: Recreate
  replicaCount: 1
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/bcgov/fin-pay-transparency/doc-gen-service
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ~
  containerPort: 3000
  environment: production
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  resources:
    limits:
      cpu: 300m
      memory: 350Mi
    requests:
      cpu: 30m
      memory: 50Mi

  podSecurityContext: {}
  securityContext: {}
  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  pdb: false

database:
  enabled: true
  image:
    registry: ghcr.io
    repository: bcgov/nr-containers/bitnami/postgresql
    tag: 15.7.0
  auth:
    existingSecret: '{{ .Release.Name }}'
    username: fin-pay-transparency
    database: fin-pay-transparency
  shmVolume:
    enabled: false
  backup:
    enabled: false
    cronjob:
      containerSecurityContext: { }
      podSecurityContext:
        enabled: false
      storage:
        size: 200Mi
  primary:
    persistence:
      enabled: true
      storageClass: netapp-block-standard
      accessModes:
        - ReadWriteOnce
      size: 100Mi
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenDeleted: Delete
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
    initdb:
      scriptsConfigMap: "{{ .Release.Name }}-database"
    resources:
      requests:
        cpu: 50m
        memory: 150Mi
      limits:
        cpu: 150m
        memory: 250Mi
