# PR specific values for fin-pay-transparency.
# Only override specific values for pr pipeline.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  secrets:
    databaseName: ~
    databaseUser: ~
    databasePassword: ~
    keycloakClientId: ~
    keycloakClientSecret: ~
    keycloakUrl: ~
    uiPrivateKey: ~
    uiPublicKey: ~
    bceidWsAuthPassword: ~
    bceidWsAuthUserName: ~
    bceidWsUrl: ~
    bceidWsOnlineServiceId: ~
  domain: "apps.silver.devops.gov.bc.ca" # it is required, apps.silver.devops.gov.bc.ca for silver cluster
  autoscaling:
    enabled: false
  crunchyEnabled: false

backend:
  deploymentStrategy: Recreate
  initResources:
    limits:
      cpu: 350m
      memory: 500Mi
    requests:
      cpu: 150m
      memory: 250Mi
  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 250Mi
  storage:
    enabled: true
    size: 50Mi
    accessMode: ReadWriteMany

frontend:
  deploymentStrategy: Recreate
  resources:
    limits:
      cpu: 30m
      memory: 150Mi
    requests:
      cpu: 15m
      memory: 50Mi
  env:
    logLevel: info

database:
  enabled: true
  deploymentStrategy: Recreate
  replicaCount: 1
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/bcgov/fin-pay-transparency/database
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ~
  podAnnotations: { }
  podSecurityContext: { }
  securityContext: { }
  imagePullSecrets: [ ]
  autoscaling:
    enabled: false
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  resources:
    limits:
      cpu: 100m
      memory: 250Mi
    requests:
      cpu: 50m
      memory: 100Mi
  persistence:
    enabled: true
    size: 60Mi
    accessMode: ReadWriteMany
    storageClass: netapp-file-standard

crunchy:
  enabled: false

