---
{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
    UPLOAD_FILE_MAX_SIZE: {{ .Values.app.env.upload_file_max_size }}

{{- end }}
