apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "database.fullname" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range tuple "seed.sql" }}
  {{ . }}: |-
        {{ $files.Get . }}
  {{- end }}