apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "database.fullname" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
data:
  seed.sql: |-
           {{ .Files.Get "seed.sql"  }}