apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
  labels: {{- include "selectorLabels" . | nindent 4 }}
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-tcp-traffic-dev-test-prod-namespace
  labels: {{- include "selectorLabels" . | nindent 4 }}
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              environment: dev
              name: db4642
    - from:
        - namespaceSelector:
            matchLabels:
              environment: test
              name: db4642
    - from:
        - namespaceSelector:
            matchLabels:
              environment: prod
              name: db4642
  policyTypes:
    - Ingress

