name: E2E
env:
  deployment_name: pay-transparency
on:
  workflow_dispatch:
    inputs:
      frontend-url:
        description: "Frontend URL of the application"
        required: true
        type: string
      environment:
        description: "Environment to read secrets from GitHub secrets"
        required: false
        default: dev
        type: string
  workflow_call:
    inputs:
      frontend-url:
        description: "Frontend URL of the application"
        required: true
        type: string
      environment:
        description: "Environment to read secrets from GitHub secrets"
        required: false
        default: dev
        type: string

jobs:
  end-to-end:
    name: Tests
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        project: [chromium, Google Chrome, firefox, safari, Microsoft Edge]
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm ci
      - name: Install Playwright dependencies
        run: npx playwright install --with-deps
      - name: Run Tests
        env:
          E2E_BASE_URL: ${{ inputs.frontend-url }}
          E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
          E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
        run: |
          npx playwright test --project=${{ matrix.project }}
      - uses: actions/upload-artifact@v4
        name: upload results
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

