name: Deploy to TEST On Workflow Dispatch.

env:
  deployment_name: pay-transparency
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The Docker Tag to deploy, it would be the latest tagged version that you want to deploy from dev to TEST."
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  image-promotions-to-test: # This is just for adding another tag to the image to reflect which docker tag is deployed to TEST.
    name: Image Promotions to TEST
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package:
          [
            backend,
            database-migrations,
            frontend,
            doc-gen-service,
            backend-external,
          ]
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: "${{ github.event.inputs.tag }}"
          tags: test
  deploys:
    name: Deploys (test)
    needs: [image-promotions-to-test]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      target: test
      environment: test
      tag: ${{ github.event.inputs.tag }}
      frontend-url: https://test.paytransparency.fin.gov.bc.ca
      semver: ${{ github.event.inputs.tag }}
      values: "values-test.yaml"
  test-integration:
    name: Integration
    needs: [deploys]
    uses: ./.github/workflows/.integration.yml
    secrets: inherit
    with:
      backend-external-url: https://pay-transparency-test-backend-external.apps.silver.devops.gov.bc.ca/api
  zap:
    name: ZAP Scan
    needs: [deploys]
    runs-on: ubuntu-22.04
    steps:
      - name: Penetration Test
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: https://test.paytransparency.fin.gov.bc.ca
          cmd_options: "-a"
          fail_action: false
          allow_issue_writing: false
