name: Deploy to PROD On Workflow Dispatch.
env:
  deployment_name: pay_transparency
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  image-promotions-to-prod:
    name: Image Promotions to PROD
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [backend, database, database-migrations, frontend]
    steps:
      - uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: test
          tags: |
           - prod
           - ${{ github.sha }}
  deploys:
    name: Deploys
    needs: image-promotions-to-prod
    environment: prod
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: generate private and public key
        id: generateKey
        shell: bash
        run: |
          EOF=" "
          ssh-keygen -t rsa -b 4096 -m PEM -f jwtRS256.key -q -N ""
          openssl rsa -in jwtRS256.key -pubout -outform PEM -out jwtRS256.key.pub
          UI_PRIVATE_KEY_VAL=$(cat jwtRS256.key)
          UI_PUBLIC_KEY_VAL=$(cat jwtRS256.key.pub)
          echo "UI_PUBLIC_KEY<<$EOF" >> $GITHUB_OUTPUT
          echo "$UI_PUBLIC_KEY_VAL" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
          
          echo "UI_PRIVATE_KEY<<$EOF" >> $GITHUB_OUTPUT
          echo "$UI_PRIVATE_KEY_VAL" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      - name: Deploy to OpenShift
        shell: bash
        run: |
          # Allow pipefail, since we could be catching oc create errors
          set +o pipefail
          
          # Login to OpenShift (NOTE: project command is a safeguard)
          oc login --token=${{ secrets.oc_token }} --server=${{ vars.oc_server }}
          oc project ${{ vars.oc_namespace }}
          
          # Deploy Helm Chart
          helm upgrade --install --wait --atomic ${{ env.deployment_name }} --values charts/fin-pay-transparency/values.yaml  --set backend.image.tag=${{ github.sha }} --set frontend.image.tag=${{ github.sha }} --set database.image.tag=${{ github.sha }} --set global.zone=prod  --set keycloakClientId="${{ secrets.KEYCLOAK_CLIENT_ID }}" --set keycloakClientSecret="${{ secrets.KEYCLOAK_CLIENT_SECRET }}" --set keycloakUrl="${{ secrets.KEYCLOAK_URL }}" --set uiPrivateKey="${{ steps.generateKey.outputs.UI_PRIVATE_KEY }}" --set uiPublicKey="${{ steps.generateKey.outputs.UI_PUBLIC_KEY }}"  --timeout 10m charts/fin-pay-transparency
  
      - name: Penetration Test
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: https://${{ env.deployment_name }}-frontend-prod.apps.silver.devops.gov.bc.ca
          cmd_options: "-a"
          fail_action: true
          allow_issue_writing: false
