name: Merge to Main

on:
  workflow_run:
    workflows: [ "Pull Request Closed" ]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  codeql:
    name: Semantic Code Analysis
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - name: Initialize
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
  deploy-init:
    name: Deploy Init to OpenShift
    environment: dev
    runs-on: ubuntu-22.04
    steps:
      - name: generate private and public key
        id: generateKey
        shell: bash
        run: |
            EOF=" "
            ssh-keygen -t rsa -b 4096 -m PEM -f jwtRS256.key -q -N ""
            openssl rsa -in jwtRS256.key -pubout -outform PEM -out jwtRS256.key.pub
            UI_PRIVATE_KEY_VAL=$(cat jwtRS256.key)
            UI_PUBLIC_KEY_VAL=$(cat jwtRS256.key.pub)
            echo "UI_PUBLIC_KEY<<$EOF" >> $GITHUB_OUTPUT
            echo "$UI_PUBLIC_KEY_VAL" >> $GITHUB_OUTPUT
            echo "$EOF" >> $GITHUB_OUTPUT
            
            echo "UI_PRIVATE_KEY<<$EOF" >> $GITHUB_OUTPUT
            echo "$UI_PRIVATE_KEY_VAL" >> $GITHUB_OUTPUT
            echo "$EOF" >> $GITHUB_OUTPUT

      - uses: bcgov-nr/action-deployer-openshift@v1.1.1
        with:
          file: common/openshift.init.yml
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: false
          parameters:
            -p ZONE=dev -p NAME=${{ github.event.repository.name }}
            -p PROMOTE=${{ github.repository }}/${{ matrix.name }}:dev
            -p KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }} -p KEYCLOAK_CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }}
            -p KEYCLOAK_URL=${{ secrets.KEYCLOAK_URL }} -p UI_PRIVATE_KEY="${{ steps.generateKey.outputs.UI_PRIVATE_KEY }}"
            -p UI_PUBLIC_KEY="${{ steps.generateKey.outputs.UI_PUBLIC_KEY }}"

  deploys-dev:
    name: Dev Deployments
    environment: dev
    needs:
      - deploy-init
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        name: [backend, database, frontend]
        include:
          - name: backend
            file: backend/openshift.deploy.yml
            parameters: -p PROMOTE_MIGRATION=${{ github.repository }}/database-migrations:dev -p CPU_REQUEST=50m -p MEMORY_REQUEST=150Mi -p CPU_LIMIT=150m -p MEMORY_LIMIT=300Mi -p MIN_REPLICAS=3 -p MAX_REPLICAS=5
            overwrite: true
          - name: database
            file: database/openshift.deploy.yml
            overwrite: false
            parameters: -p CPU_REQUEST=100m -p MEMORY_REQUEST=150Mi -p CPU_LIMIT=250m -p MEMORY_LIMIT=250Mi
          - name: frontend
            file: frontend/openshift.deploy.yml
            overwrite: true
            parameters: -p CPU_REQUEST=25m -p MEMORY_REQUEST=40Mi -p CPU_LIMIT=75m -p MEMORY_LIMIT=80Mi -p MIN_REPLICAS=3 -p MAX_REPLICAS=5

    steps:
      - uses: bcgov-nr/action-deployer-openshift@v1.1.1
        with:
          file: ${{ matrix.file }}
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: ${{ matrix.overwrite }}
          parameters:
            -p ZONE=dev -p PROMOTE=${{ github.repository }}/${{ matrix.name }}:dev
            -p NAME=${{ github.event.repository.name }} ${{ matrix.parameters }}
          penetration_test: true

