name: Deploy to PROD On Workflow Dispatch.
env:
  deployment_name: pay-transparency
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The Docker Tag to deploy, it would be the latest tagged version that you want to deploy from TEST to PROD.'
        required: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  image-promotions-to-prod: # This is just for adding another tag to the image to reflect which docker tag is deployed to PROD.
    name: Image Promotions to PROD
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [backend, database, database-migrations, frontend]
    steps:
      - uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: "${{ github.event.inputs.tag }}"
          tags: prod
  deploys:
    name: Deploys (prod)
    needs: [ image-promotions-to-prod ]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      target: prod
      environment: prod
      tag: ${{ github.event.inputs.tag }}
      penetration-test: false
      frontend-url: https://paytransparency.fin.gov.bc.ca

