name: Merge to Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/*"
      - "**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:

  deploys-dev:
    name: Dev Deployments
    environment: dev
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        name: [backend, database, frontend, init]
        include:
          - name: backend
            file: backend/openshift.deploy.yml
            parameters: -p PROMOTE_MIGRATION=${{ github.repository }}/database-migrations:dev -p KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }} -p KEYCLOAK_CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }} -p KEYCLOAK_URL=${{ secrets.KEYCLOAK_URL }}
            overwrite: true
          - name: database
            file: database/openshift.deploy.yml
            overwrite: false
          - name: frontend
            file: frontend/openshift.deploy.yml
            overwrite: true
          - name: init
            file: common/openshift.init.yml
            overwrite: false
    steps:
      - uses: bcgov-nr/action-deployer-openshift@v1.1.1
        with:
          file: ${{ matrix.file }}
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: ${{ matrix.overwrite }}
          parameters:
            -p ZONE=dev -p PROMOTE=${{ github.repository }}/${{ matrix.name }}:dev
            -p NAME=${{ github.event.repository.name }} ${{ matrix.parameters }}

          penetration_test: true

