name: Build And Deploy to Sandbox in Dev namespace
env:
  DOMAIN: apps.silver.devops.gov.bc.ca
  PREFIX: pay-transparency-pr-${{ github.event.number }}
on:
  pull_request:
    branches:
      - main

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: pr-${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  pr-description-add:
    name: PR Description Add
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    timeout-minutes: 1
    steps:
      - uses: bcgov-nr/action-pr-description-add@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_markdown: |
            ---
            Thanks for the PR!
            
            Deployments, as required, will be available below:
            - [Frontend](https://${{ env.PREFIX }}-frontend.${{ env.DOMAIN }})
            
  builds:
    if: '!github.event.pull_request.head.repo.fork'
    name: Build Containers for OpenShift Deployment
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [backend, database, database-migrations, frontend]
        include:
          - package: backend
            triggers: ('backend/')
            build_file: ./backend/Dockerfile
            build_context: ./backend
          - package: database
            triggers: ('database/')
            build_file: ./database/Dockerfile
            build_context: ./database
          - package: frontend
            triggers: ('frontend/')
            build_file: ./frontend/Dockerfile
            build_context: ./frontend
          - package: database-migrations
            triggers: ('backend/db')
            build_file: ./backend/db/Dockerfile
            build_context: ./backend/db

    steps:
      - uses: actions/checkout@v4
      - uses: bcgov-nr/action-builder-ghcr@v2.0.0
        with:
          package: ${{ matrix.package }}
          tag: ${{ github.event.number }}
          tag_fallback: test
          triggers: ${{ matrix.triggers }}
          build_context: ${{ matrix.build_context }}

      - uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ github.event.number }}
          tags: |
            pr-${{ github.event.number }}
            ${{ github.sha }}
            ${{ github.event.number }}


  deploys:
    name: Deploys
    needs: [builds]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      autoscaling: false
      target: pr-${{ github.event.number }}
      tag: ${{ github.sha }}
      values: 'values-pr.yaml'
      frontend_url: https://${{ env.PREFIX }}-frontend.${{ env.DOMAIN }}

