name: Pull Request Closed

on:
  pull_request:
    branches:
      - main
    types:
      - closed

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: pr-${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  # Clean up OpenShift when PR closed, no conditions
  cleanup-openshift:
    if: '!github.event.pull_request.head.repo.fork'
    name: Cleanup OpenShift
    env:
      release: pay-transparency-pr-${{ github.event.number }}
    runs-on: ubuntu-22.04
    steps:
      - name: Remove OpenShift artifacts
        run: |
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ vars.OC_SERVER }}
          oc project ${{ vars.OC_NAMESPACE }}

          helm status ${{ env.release }} && helm uninstall --no-hooks ${{ env.release }} || \
            echo "Not found: ${{ env.release }}"

  # If merged into main, then handle any image promotions
  image-promotions:
    name: Image Promotions
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [backend, database, database-migrations, frontend]
    steps:
      - uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ github.event.number }}
          tags: |
            dev
            ${{ github.sha }}
